[theme]
base = "light"
primaryColor = "#ffcb05"
backgroundColor = "#f8f9fd"
secondaryBackgroundColor = "#e8ecf7"
textColor = "#191970"
font = "sans serif"

[server]
port = 8501
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
